name: Tag Release

on:
  push:
    branches:
      - main
      - staging
      - dev

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get the branch name
        id: get_branch
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch name: $branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the latest tag on relevant branch
        id: get_latest_tag
        run: |
          if [ "${{ env.branch_name }}" = "main" ]; then
            latest_source_tag=$(git tag -l --sort=-v:refname "*-staging" | head -n 1)
            if [ -z "$latest_source_tag" ]; then
              latest_source_tag="1.0.0-staging"
            fi
          elif [ "${{ env.branch_name }}" = "staging" ]; then
            latest_source_tag=$(git tag -l --sort=-v:refname "*-dev" | head -n 1)
            if [ -z "$latest_source_tag" ]; then
              latest_source_tag="1.0.0-dev"
            fi
          elif [ "${{ env.branch_name }}" = "dev" ]; then
            latest_source_tag=$(git tag -l --sort=-v:refname "*-dev" | head -n 1)
            if [ -z "$latest_source_tag" ]; then
              latest_source_tag="1.0.0-dev"
            fi
          fi
          echo "latest_source_tag=$latest_source_tag" >> $GITHUB_ENV

      - name: Get the latest tag on current branch
        id: current_tag
        run: |
          current_latest_tag=$(git tag -l --sort=-v:refname "*-${{ env.branch_name }}" | head -n 1)
          if [ -z "$current_latest_tag" ]; then
            current_latest_tag="1.0.0-${{ env.branch_name }}"
          fi
          echo "current_latest_tag=$current_latest_tag" >> $GITHUB_ENV

      - name: Compare and determine new tag version
        id: new_tag_version
        run: |
          if [ "${{ env.branch_name }}" = "dev" ]; then
            latest_tag=${{ env.latest_source_tag }}
            dev_version=${latest_tag%-dev}

            IFS='.' read -r -a version_parts <<< "$dev_version"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}

            increment_type="patch"
            if git log -1 --pretty=%B | grep -q 'major'; then
              increment_type="major"
            elif git log -1 --pretty=%B | grep -q 'feature'; then
              increment_type="minor"
            fi

            case $increment_type in
              major)
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              minor)
                minor=$((minor + 1))
                patch=0
                ;;
              patch)
                patch=$((patch + 1))
                ;;
            esac

            new_tag="$major.$minor.$patch-dev"
          else
            compare_versions() {
              printf '%s\n%s' "$1" "$2" | sort -V | tail -n1
            }

            latest_source_tag=${{ env.latest_source_tag }}
            if [ "${{ env.branch_name }}" = "staging" ]; then
              source_version=${latest_source_tag%-dev}
            elif [ "${{ env.branch_name }}" = "main" ]; then
              source_version=${latest_source_tag%-staging}
            fi
          
            current_latest_tag=${{ env.current_latest_tag }}
            current_version=${current_latest_tag%-${{ env.branch_name }}}

            new_version=$(compare_versions "$source_version" "$current_version")
            new_tag="${new_version}-${{ env.branch_name }}"
          fi

          echo "New tag version: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Set the KEY_PREFIX
        run: |
          if [ "${{ env.branch_name }}" = "main" ]; then
            echo "KEY_PREFIX=prod" >> $GITHUB_ENV
          else
            echo "KEY_PREFIX=${{ env.branch_name }}" >> $GITHUB_ENV
          fi

      - name: Configure git to use GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Check if tag exists
        id: check_tag
        run: |
          new_tag=${{ env.new_tag }}
          if git rev-parse "$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists"
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Create and push the new tag with branch name
        if: env.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag=${{ env.new_tag }}

          git tag $new_tag
          git push origin $new_tag

      - name: Update new version in dashboard config DB through API
        if: env.tag_exists == 'false'
        env:
          API_URL: https://dashboard.plug2win.com/api/config
          KEY_PREFIX: ${{ env.KEY_PREFIX }}
        run: |
          curl -X POST $API_URL \
            -H "Content-Type: application/json" \
            -d '{"key":"client_'${KEY_PREFIX}'_githubVersion", "value": "${{ env.new_tag }}", "secret": "${{ secrets.DASHBOARD_SECRET }}" }'

      - name: Output the new tag
        if: env.tag_exists == 'false'
        run: |
          echo "New tag created: ${{ env.new_tag }}"

      - name: Output existing tag
        if: env.tag_exists == 'true'
        run: |
          echo "Tag ${{ env.new_tag }} already exists"
